In [2]:
import pandas as pd 
import numpy as np

In [6]:
pd.read_csv('restaurants_data.csv')

,Place ID,Name,Summary,Price Level,Address,Latitude,Longitude,Overall Rating,Opening Hours,Total Reviews,Reviews,Review Ratings
0,ChIJgVEdThRQqEcRSOFGvzG1HJY,PapalaCup,Relaxed choice with a retro ambiance serving c...,2.0,"Gotenstraße 55, Berlin-Bezirk Tempelhof-Schöne...",52.479837,13.360437,4.7,"Monday: Closed, Tuesday: 9:00 AM – 5:00 PM, We...",656.0,"['First time trying this place, very positive ...","[5, 5, 5]"
1,ChIJA4aYMRFQqEcRH6uBnGsZCsk,Burger King,Well-known fast-food chain serving grilled bur...,2.0,"General-Pape-Straße 1, Berlin",52.476453,13.364784,2.9,"Monday: 10:00 AM – 11:00 PM, Tuesday: 10:00 AM...",922.0,['Well packed take away and friendly staff.\n\...,"[4, 1, 1]"
2,ChIJy3vdsCROqEcRN_KQfhojoAM,Ming Dynastie Jannowitzbrücke Berlin,Chinese restaurant with a wood-paneled dining ...,2.0,"Brückenstraße 6, Berlin",52.513664,13.418460,4.5,"Monday: 12:00 – 9:30 PM, Tuesday: 12:00 – 10:0...",3237.0,['I think this restaurant is better southern C...,"[4, 5, 4]"
3,ChIJ8dE5ZzlOqEcRSOv8JF88prM,Katerschmaus,Stylishly presented grilled meats & fish dishe...,3.0,"Holzmarktstraße 25, Berlin-Bezirk Friedrichsha...",52.511171,13.426656,4.3,"Monday: 12:00 – 3:00 PM, 6:00 – 10:00 PM, Tues...",1135.0,"[""we didn't have a reservation, luckily we fou...","[5, 5, 4]"
4,ChIJSTDULz9OqEcR1zoGQzd7sCI,Trattoria La Bruschetta,Comfortable restaurant specializing in classic...,2.0,"Andreasstraße 66, Berlin-Bezirk Friedrichshain...",52.513399,13.431085,4.7,"Monday: 12:00 – 11:00 PM, Tuesday: 12:00 – 11:...",1564.0,['This is a perfect restaurant. The food is ju...,"[5, 3, 5]"
...,...,...,...,...,...,...,...,...,...,...,...,...
395,ChIJ78XOQEpQqEcRBalVhfFOZjg,Burger King,Well-known fast-food chain serving grilled bur...,2.0,"Potsdamer Straße 114, Berlin",52.500514,13.363134,3.4,"Monday: 10:00 AM – 1:00 AM, Tuesday: 10:00 AM ...",1445.0,['Pretty small Burger King. If the store is pa...,"[4, 1, 1]"
396,ChIJN89il0pQqEcRnj_fG-XYIUM,Joseph-Roth-Diele,"Classic schnitzel, dumplings & potato salad in...",1.0,"Potsdamer Straße 75, Berlin",52.502566,13.365633,4.4,"Monday: Closed, Tuesday: 10:00 AM – 10:00 PM, ...",1395.0,"['Very good service and nice vibe, but the foo...","[4, 5, 4]"
397,ChIJr3lysEpQqEcRUlmcg2qXzcE,Dalmacija Grill,Homestyle Croatian meat & seafood grills in a ...,1.0,"Potsdamer Straße 84, Berlin",52.503493,13.365702,4.6,"Monday: 11:30 AM – 11:00 PM, Tuesday: Closed, ...",1251.0,['Outstanding food and service. The dishes tha...,"[5, 5, 5]"
398,ChIJ8_3EIktQqEcRbv6fKXE3Wr0,Kin Dee,Modern takes on classic Thai curries & noodle ...,3.0,"Lützowstraße 81, Berlin",52.503519,13.362370,4.0,"Monday: Closed, Tuesday: 6:00 – 11:00 PM, Wedn...",533.0,['A pleasant surprised for us to walk-in & abl...,"[5, 5, 3]"
399,ChIJf8ZafEpQqEcRUAZQT-9cLkE,"OH, PANAMA",Wine pairings & creative takes on regional dis...,3.0,"Potsdamer Straße 91, Berlin",52.501479,13.364748,4.5,"Monday: Closed, Tuesday: 6:00 PM – 1:00 AM, We...",1111.0,['The overall note would be between 3 and 4 b...,"[3, 5, 5]"

In [4]:
pd.read_csv('user_restaurants.csv')

,Place ID,Name,Summary,Price Level,Address,Latitude,Longitude,Overall Rating,Opening Hours,Total Reviews,Reviews,Review Ratings
0,ChIJXaMnx5tPqEcRGOVrSo2iSQ0,leuchtstoff - Kaffeebar und Bakery,Cozy couches & hip music selections in a busy ...,2.0,"Siegfriedstraße 18, Berlin-Bezirk Neukölln",52.468124,13.432499,4.5,"Monday: 7:30 AM – 6:00 PM, Tuesday: 7:30 AM – ...",656,['I love this place! They have amazing coffee ...,"[5, 3, 2]"
1,ChIJH3GIbJtPqEcRiGkSKyp4LIk,Asude Yemek Dünyası,Generously portioned homestyle Turkish dishes ...,1.0,"Hermannstraße 120, Berlin-Bezirk Neukölln",52.465688,13.432044,4.4,"Monday: 5:00 AM – 2:00 AM, Tuesday: 5:00 AM – ...",1421,"[""My favourite halal restaurant in Berlin. Wen...","[5, 5, 5]"
2,ChIJScNbb5tPqEcRcVs-V5hxjLQ,Pho Phan,"Vietnamese pho noodle soups, spring rolls & Th...",1.0,"Hermannstraße 151, Berlin-Bezirk Neukölln",52.465606,13.432599,4.4,"Monday: 11:30 AM – 11:00 PM, Tuesday: 11:30 AM...",1218,['Super nice restaurant. The food is delicious...,"[5, 5, 3]"
3,ChIJ2fwmCZNPqEcR3cGvIgphsLY,Mira Restaurant,Casual fixture serving globally inspired break...,NaN,"Hermannstraße 157, Berlin-Bezirk Neukölln",52.466784,13.432084,4.3,"Monday: 8:00 AM – 1:00 AM, Tuesday: 8:00 AM – ...",1425,"['We stopped in here for breakfast, and in all...","[5, 5, 5]"
4,ChIJxcPlm0tPqEcRhOa2cqnzxtc,Anh Em Restaurant,Unassuming eatery fixing up Asian staples incl...,2.0,"Hermannstraße 154, Berlin-Bezirk Neukölln",52.466159,13.432359,4.7,"Monday: 12:00 – 10:30 PM, Tuesday: 12:00 – 10:...",744,['Asian Fusion dishes in a rustic-chic Vietnam...,"[5, 5, 4]"
...,...,...,...,...,...,...,...,...,...,...,...,...
211,ChIJXfXRYOVRqEcR530Cu7eIzrg,ASMAN,"Colorful, down-to-earth restaurant offering sp...",1.0,"Ackerstraße 20, Berlin",52.531575,13.396603,4.0,"Monday: 12:00 PM – 12:00 AM, Tuesday: 12:00 PM...",427,"['Nice place, food was tasty but the service c...","[3, 5, 4]"
212,ChIJzxxz9eVRqEcRX2oG338jQnY,Bandol sur mer,"Industrial-chic haunt with an open kitchen, of...",4.0,"Torstraße 167, Berlin",52.529138,13.395454,4.6,"Monday: 6:30 – 11:00 PM, Tuesday: 6:30 – 11:00...",305,['At the start of the evening if there is spac...,"[5, 5, 4]"
213,ChIJm3_SgO9RqEcRPsCFGSCiw4U,Cafe Ribo,Unpretentious weekdays-only outfit serving dum...,NaN,"Ackerstraße 157, Berlin",52.530891,13.396628,4.7,"Monday: 11:30 AM – 8:00 PM, Tuesday: 11:30 AM ...",66,"[""Such a pleasant surprise, in the midst of mi...","[5, 5, 5]"
214,ChIJt9YYofpRqEcROz2RETsyOS0,Chay Viet Berlin,"Vegetarian pho soups, cold rolls & Vietnamese ...",1.0,"Brunnenstraße 164, Berlin",52.534129,13.397946,4.4,"Monday: 11:30 AM – 10:00 PM, Tuesday: 11:30 AM...",1009,['Simply amazing!! One of the best meals I’ve ...,"[5, 4, 5]"
215,ChIJcV4RfQFSqEcRAH6ehsDH0BI,Villa Rodizio,"High-ceilinged, art nouveau venue combining ch...",2.0,"Milastraße 2, Berlin-Bezirk Pankow",52.545466,13.411464,4.4,"Monday: Closed, Tuesday: 6:00 – 11:00 PM, Wedn...",5602,"[""Enjoyable Rodizio style restaurant on the ou...","[4, 5, 5]"

In [7]:
pd.read_csv('random_user_historical_data.csv')

,user_id,Place ID,Name,Summary,Price Level,Address,Latitude,Longitude,Overall Rating,Opening Hours,Total Reviews,Reviews,Review Ratings,user_ratings,visit_date,visit_time
0,1,ChIJLT1gFNtRqEcRUIdXWAGRLB8,Restaurant Austernbank,"Upscale seafood plates presented in a grand, s...",NaN,"Behrenstraße 42, Berlin",52.515929,13.391821,4.3,"Monday: Closed, Tuesday: 5:00 PM – 1:00 AM, We...",323,"[""Was ok, I guess...\nI'd say everything was a...","[4, 5, 2]",1,2023-12-10 20:34:25.536555,14:02:46
1,1,ChIJOeDFuFtOqEcRE8S2p2Wcu-c,Trattoria Libau,Unassuming operation with an old-school vibe d...,2.0,"Libauer Straße 10, Berlin-Bezirk Friedrichshai...",52.508665,13.452836,4.5,"Monday: 4:00 PM – 12:00 AM, Tuesday: 4:00 PM –...",1116,['Good place for a quick Italian food. The piz...,"[4, 5, 5]",5,2024-07-27 20:34:25.536559,17:40:19
2,1,ChIJQUz4iklQqEcRoR2HY1JwkQE,Fadi Food,Unpretentious restaurant serving shawarma wrap...,1.0,"Potsdamer Straße 117, Berlin-Bezirk Tempelhof-...",52.498779,13.362772,4.2,"Monday: 7:00 AM – 11:00 PM, Tuesday: 7:00 AM –...",840,['Amazingly decent food that tastes exactly li...,"[5, 5, 5]",4,2023-09-24 20:34:25.536540,18:57:03
3,1,ChIJrfRNQslPqEcRPuCFqF0-DMI,St. Bart,Bar & kitchen with simple tiled décor plating ...,2.0,"Graefestraße 71, Berlin-Bezirk Friedrichshain-...",52.491920,13.417182,4.5,"Monday: 6:00 – 11:30 PM, Tuesday: 6:00 – 11:30...",664,['Really tasty meal and superb experience! All...,"[5, 4, 3]",3,2024-06-25 20:34:25.536563,10:54:32
4,2,ChIJ4Vof-khQqEcR1CPHIeU2ud4,Nafis Restaurant,"This small, modest Persian spot with tradition...",2.0,"Winterfeldtstraße 11, Berlin-Bezirk Tempelhof-...",52.496140,13.359165,4.3,"Monday: Closed, Tuesday: 11:30 AM – 10:30 PM, ...",639,"[""Super fair prices for tasty, authentic Irani...","[5, 4, 5]",5,2023-10-07 20:34:25.536566,13:08:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,99,ChIJ_8i7pJFPqEcRxmFgAssALik,Taverna Olympia,Mediterranean standards like meze & gyros in a...,2.0,"Emser Straße 73, Berlin-Bezirk Neukölln",52.467257,13.421398,4.6,"Monday: 4:30 – 11:00 PM, Tuesday: Closed, Wedn...",668,['Excellent food and superb service. Very conv...,"[5, 5, 4]",4,2023-10-16 20:34:25.537566,10:59:57
352,99,ChIJhYcCg_RRqEcR2BHrK-3C_nI,Café & Bistro freysinn,"Salads, soups & pasta dishes, plus vegetarian ...",2.0,"Jasmunder Straße 5, Berlin",52.539842,13.388170,4.3,"Monday: 8:00 AM – 3:00 PM, Tuesday: 8:00 AM – ...",194,"['Delicious food, you can go every day and you...","[5, 2, 5]",2,2023-11-09 20:34:25.537572,19:49:43
353,100,ChIJFRjYpfpRqEcRzQcG_2x5Hvk,The Tree,"Szechuan rice bowls, noodle soups & small plat...",2.0,"Brunnenstraße 167, Berlin",52.533774,13.398074,4.6,"Monday: 12:00 – 3:00 PM, 5:30 – 10:00 PM, Tues...",1004,"['The interior design is very creative, with a...","[4, 5, 4]",5,2024-09-07 20:34:25.537580,20:55:47
354,100,ChIJN1PxiuBTqEcRFCOAciXXaCc,Baba đu Restaurant,Hip eatery in an industrial-style space with o...,2.0,"Breite Straße 50, Berlin",52.572023,13.414880,4.8,"Monday: 11:00 AM – 10:00 PM, Tuesday: 11:00 AM...",871,"[""Nice selection of dishes. We initially came ...","[4, 5, 5]",1,2023-10-06 20:34:25.537583,20:30:34
355,100,ChIJjdxZF8lRqEcREcbD8THB3gk,Vapiano,Laid-back restaurant featuring made-to-order f...,2.0,"Potsdamer Platz 5, Berlin",52.510234,13.376361,3.4,"Monday: 11:00 AM – 11:00 PM, Tuesday: 11:00 AM...",5513,"[""My recent experience at this restaurant was ...","[1, 4, 4]",3,2024-05-28 20:34:25.537578,21:15:53